### ISSUE TITLE
FPX_SELLER_ID variable name mismatched

### ISSUE THREAD

**Issue by Jagdish-J-P** [aimensasi/fpx#2] opened 2021-06-14 09:53 UTC
This variable **FPX_SELLER_ID** should be **FPX_Seller_ID**

**Comment by aimensasi** [comment] 2021-06-16 03:49
Which part are you taking about, can you provide a screenshot or a snippt

**Comment by Jagdish-J-P** [comment] 2021-06-16 05:38
![2021-06-16 (2)](https://user-images.githubusercontent.com/20887370/122163497-ee178d00-ce92-11eb-82cb-1ff816ff3c1f.png)
![2021-06-16 (3)](https://user-images.githubusercontent.com/20887370/122163504-f243aa80-ce92-11eb-9fd5-ce578ce798c5.png)

I am talking about this. In README file you have written **FPX_SELLER_ID** but in your config file it is written as **env('FPX_Seller_ID')**. I don't know if env() function works case-insensitive or not.

**Comment by aimensasi** [comment] 2021-06-16 06:33
Thanks for letting me know. The issue is Fixed in #4

**Closed as completed by aimensasi** 2021-06-16 06:33 UTC
